In [1]:
import pandas as pd
races_2023 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2023season_raceResults.csv")
quali_2023 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2023season_qualifyingResults.csv")
drivers_2023 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2023season_drivers.csv")
teams_2023 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2023season_teams.csv")
calendar_2023 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2023season_calendar.csv")

In [4]:
races_2023.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:33:56.736,25,No,1:36.236
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,2,57,+11.987,18,No,1:36.344
2,Bahrain,3,14,Fernando Alonso,Aston Martin Aramco Mercedes,5,57,+38.637,15,No,1:36.156
3,Bahrain,4,55,Carlos Sainz,Ferrari,4,57,+48.052,12,No,1:37.130
4,Bahrain,5,44,Lewis Hamilton,Mercedes,7,57,+50.977,10,No,1:36.546

In [5]:
races_2023.columns
races_2023.dtypes

Track               object
Position            object
No                   int64
Driver              object
Team                object
Starting Grid        int64
Laps                 int64
Time/Retired        object
Points               int64
Set Fastest Lap     object
Fastest Lap Time    object
dtype: object

In [6]:
races_2024 = pd.read_csv("formula1-datasets-master/formula1-datasets-master/Formula1_2024season_raceResults.csv")

In [7]:
races_2024.head()

,Track,Position,No,Driver,Team,Starting Grid,Laps,Time/Retired,Points,Set Fastest Lap,Fastest Lap Time
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1,57,1:31:44.742,26,Yes,1:32.608
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,5,57,+22.457,18,No,1:34.364
2,Bahrain,3,55,Carlos Sainz,Ferrari,4,57,+25.110,15,No,1:34.507
3,Bahrain,4,16,Charles Leclerc,Ferrari,2,57,+39.669,12,No,1:34.090
4,Bahrain,5,63,George Russell,Mercedes,3,57,+46.788,10,No,1:35.065

In [9]:
races_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479 entries, 0 to 478
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Track             479 non-null    object
 1   Position          479 non-null    object
 2   No                479 non-null    int64
 3   Driver            479 non-null    object
 4   Team              479 non-null    object
 5   Starting Grid     479 non-null    int64
 6   Laps              479 non-null    int64
 7   Time/Retired      479 non-null    object
 8   Points            479 non-null    int64
 9   Set Fastest Lap   479 non-null    object
 10  Fastest Lap Time  463 non-null    object
dtypes: int64(4), object(7)
memory usage: 41.3+ KB