# Filler_Dataset_Collection_&_Filtering_&_Analysis

In [3]:
import pandas as pd

## importing datasets

In [4]:
circuits = pd.read_csv("filler-datasets/circuits.csv")
drivers = pd.read_csv("filler-datasets/drivers.csv")
results = pd.read_csv("filler-datasets/results.csv")
races = pd.read_csv("filler-datasets/races.csv")

In [3]:
circuits.head()

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [4]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [5]:
results.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [7]:
races.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

### Removing unncessary colummns from Races

In [14]:
races = races[['raceId', 'year','round','circuitId','name']]

In [15]:
races.head()

   raceId  year  round  circuitId                   name
0       1  2009      1          1  Australian Grand Prix
1       2  2009      2          2   Malaysian Grand Prix
2       3  2009      3         17     Chinese Grand Prix
3       4  2009      4          3     Bahrain Grand Prix
4       5  2009      5          4     Spanish Grand Prix

### Removing unncessary colummns from Results

In [17]:
results = results[['resultId','raceId','driverId','position','time','milliseconds','fastestLapTime','fastestLapSpeed']]

In [18]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

### Removing unncessary colummns from Races

In [19]:
drivers = drivers[['driverId','driverRef','code','forename','surname']]

### Saving Temp Datasets

In [20]:
races.to_csv('races_filtered.csv', index=False)
drivers.to_csv('drivers_filtered.csv', index=False)
results.to_csv('results_filtered.csv', index=False)

In [21]:
races.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   raceId     1125 non-null   int64
 1   year       1125 non-null   int64
 2   round      1125 non-null   int64
 3   circuitId  1125 non-null   int64
 4   name       1125 non-null   object
dtypes: int64(4), object(1)
memory usage: 44.1+ KB

### Keeps rows where Year is between 2018 and 2025 (inclusive)

In [25]:
# Keeps rows where Year is between 2018 and 2025 (inclusive)
races_filtered = races[races['year'].between(2018, 2025)]

In [27]:
races_filtered.head()

     raceId  year  round  circuitId                   name
976     989  2018      1          1  Australian Grand Prix
977     990  2018      2          3     Bahrain Grand Prix
978     991  2018      3         17     Chinese Grand Prix
979     992  2018      4         73  Azerbaijan Grand Prix
980     993  2018      5          4     Spanish Grand Prix

In [63]:
# Returns the last row as a Series
results.tail(1)

,resultId,raceId,driverId,position,time,milliseconds,fastestLapTime,fastestLapSpeed
26758,26764,1144,815,\N,\N,\N,\N,\N

#### Only keeping races between 2018 and 2025

In [36]:
results_filtered = results[results['raceId'].between(989, 1144)]

In [37]:
results_filtered.head()

,resultId,raceId,driverId,position,time,milliseconds,fastestLapTime,fastestLapSpeed
23777,23782,989,20,1,1:29:33.283,5373283,1:26.469,220.782
23778,23783,989,1,2,+5.036,5378319,1:26.444,220.845
23779,23784,989,8,3,+6.309,5379592,1:26.373,221.027
23780,23785,989,817,4,+7.069,5380352,1:25.945,222.128
23781,23786,989,4,5,+27.886,5401169,1:26.978,219.489

In [64]:
# verifying all races are mentioned
races_filtered['year'].value_counts()

year
2024    24
2021    22
2022    22
2023    22
2018    21
2019    21
2020    17
Name: count, dtype: int64

In [43]:
races_filtered.to_csv('races_filtered.csv', index=False)
results_filtered.to_csv('results_filtered.csv', index=False)

## Filtering Drivers

In [45]:
drivers.info()
#we do not need all drivers

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   driverId   861 non-null    int64
 1   driverRef  861 non-null    object
 2   code       861 non-null    object
 3   forename   861 non-null    object
 4   surname    861 non-null    object
dtypes: int64(1), object(4)
memory usage: 33.8+ KB

### Filtering drivers from 2018-2025

In [47]:
values = results_filtered['driverId'].value_counts()

In [50]:
values.info()

<class 'pandas.core.series.Series'>
Index: 40 entries, 822 to 862
Series name: count
Non-Null Count  Dtype
--------------  -----
40 non-null     int64
dtypes: int64(1)
memory usage: 1.7 KB

In [51]:
unique_driver_ids = values.index.to_numpy()

In [55]:
len(unique_driver_ids)
#40 unique drivers

40

### Mapping the driver's info from Drivers dataset

In [57]:
# 1. Filter the dataset based on the NumPy array
# This keeps only rows where driverId is in your list
filtered_drivers = drivers[drivers['driverId'].isin(unique_driver_ids)]
# 2. Select only the specific columns you want
driver_dataset_ = filtered_drivers[['driverId', 'driverRef', 'code','forename','surname']]

In [60]:
#final drivers dataset with drivers who participated from 2018
driver_dataset_.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40 entries, 0 to 860
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   driverId   40 non-null     int64
 1   driverRef  40 non-null     object
 2   code       40 non-null     object
 3   forename   40 non-null     object
 4   surname    40 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.9+ KB

In [61]:
driver_dataset_.to_csv('drivers_filtered.csv', index=False)

# ROUGH

In [7]:
drivers[drivers['forename']=='Max']

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
348,349,jean,\N,\N,Max,Jean,1943-07-27,French,http://en.wikipedia.org/wiki/Max_Jean
720,720,terra,\N,\N,Max,de Terra,1918-10-06,Swiss,http://en.wikipedia.org/wiki/Max_de_Terra
819,820,chilton,4,CHI,Max,Chilton,1991-04-21,British,http://en.wikipedia.org/wiki/Max_Chilton
829,830,max_verstappen,33,VER,Max,Verstappen,1997-09-30,Dutch,http://en.wikipedia.org/wiki/Max_Verstappen

In [11]:
results_filtered = pd.read_csv('filler-datasets/results_filtered.csv')

In [23]:
results_filtered.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2979 entries, 0 to 2978
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         2979 non-null   int64
 1   raceId           2979 non-null   int64
 2   driverId         2979 non-null   int64
 3   position         2979 non-null   object
 4   time             2979 non-null   object
 5   milliseconds     2979 non-null   object
 6   fastestLapTime   2979 non-null   object
 7   fastestLapSpeed  2979 non-null   object
dtypes: int64(3), object(5)
memory usage: 186.3+ KB

In [35]:
season_res = pd.read_csv('all-dataset-processed(initial)/Formula1_2023season_qualifyingResults.csv')

In [36]:
season_res.head()

,Track,Position,No,Driver,Team,Q1,Q2,Q3,Laps,kaggle_driver_id
0,Bahrain,1,1,Max Verstappen,Red Bull Racing Honda RBPT,1:31.295,1:30.503,1:29.708,15,830
1,Bahrain,2,11,Sergio Perez,Red Bull Racing Honda RBPT,1:31.479,1:30.746,1:29.846,15,815
2,Bahrain,3,16,Charles Leclerc,Ferrari,1:31.094,1:30.282,1:30.000,17,844
3,Bahrain,4,55,Carlos Sainz,Ferrari,1:30.993,1:30.515,1:30.154,18,832
4,Bahrain,5,14,Fernando Alonso,Aston Martin Aramco Mercedes,1:31.158,1:30.645,1:30.336,15,4

In [37]:
sprint_res = pd.read_csv('all-dataset-processed(initial)/Formula1_2024season_sprintQualifyingResults.csv')

In [38]:
sprint_res.head()

,Track,Position,No,Driver,Team,Q1,Q2,Q3,Laps,kaggle_driver_id
0,China,1,4,Lando Norris,McLaren Mercedes,1:36.384,1:36.047,1:57.940,13,846
1,China,2,44,Lewis Hamilton,Mercedes,1:37.181,1:36.287,1:59.201,15,1
2,China,3,14,Fernando Alonso,Aston Martin Aramco Mercedes,1:36.883,1:36.119,1:59.915,14,4
3,China,4,1,Max Verstappen,Red Bull Racing Honda RBPT,1:36.456,1:35.606,2:00.028,12,830
4,China,5,55,Carlos Sainz,Ferrari,1:36.719,1:36.052,2:00.214,15,832

In [42]:
sprint_kaggle_res = pd.read_csv('filler-datasets/sprint_results.csv')
sprint_kaggle_res.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1

In [43]:
race_kaggle = pd.read_csv('filler-datasets/races_filtered.csv')
race_kaggle.head()

   raceId  year  round  circuitId                   name
0     989  2018      1          1  Australian Grand Prix
1     990  2018      2          3     Bahrain Grand Prix
2     991  2018      3         17     Chinese Grand Prix
3     992  2018      4         73  Azerbaijan Grand Prix
4     993  2018      5          4     Spanish Grand Prix

In [44]:
race_kaggle['name'].value_counts()

name
Bahrain Grand Prix             7
British Grand Prix             7
Hungarian Grand Prix           7
Spanish Grand Prix             7
Italian Grand Prix             7
Belgian Grand Prix             7
Abu Dhabi Grand Prix           7
Austrian Grand Prix            7
United States Grand Prix       6
Monaco Grand Prix              6
Azerbaijan Grand Prix          6
Australian Grand Prix          5
Canadian Grand Prix            5
Japanese Grand Prix            5
Singapore Grand Prix           5
São Paulo Grand Prix           4
Russian Grand Prix             4
Dutch Grand Prix               4
Emilia Romagna Grand Prix      4
French Grand Prix              4
Mexico City Grand Prix         4
Saudi Arabian Grand Prix       4
Chinese Grand Prix             3
Qatar Grand Prix               3
Miami Grand Prix               3
Brazilian Grand Prix           2
German Grand Prix              2
Mexican Grand Prix             2
Styrian Grand Prix             2
Portuguese Grand Prix          2
Las Vegas Grand Prix           2
Turkish Grand Prix             2
Eifel Grand Prix               1
Tuscan Grand Prix              1
70th Anniversary Grand Prix    1
Sakhir Grand Prix              1
Name: count, dtype: int64

In [45]:
race_kaggle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   raceId     149 non-null    int64
 1   year       149 non-null    int64
 2   round      149 non-null    int64
 3   circuitId  149 non-null    int64
 4   name       149 non-null    object
dtypes: int64(4), object(1)
memory usage: 5.9+ KB